### ISSUE TITLE
Add support for .hint and .desc files

### ISSUE THREAD

**Issue by Tagl** [Kodsport/testdata_tools#18]
I'm not sure what the best format for this would be but I think it would be useful to be able to associate a hint or description with a generated testcase.
I'd like to hear your thoughts on this and how you'd envision the API for it.
My current idea is simply a command such as `set_hint` or `set_desc` that prepares hint or desc configuration before calling tc.

**Comment by simonlindholm** [comment]
That sounds reasonable. It could also apply to the test case just before; either way.

For the Swedish IOI qualifiers we've never felt a need for this feature; as judges it's enough to look at file names and at generator.sh to get an idea of what the test case is about, to the extent we do that at all, and we never expose information of this kind to contestants. If we wanted to use it for a single problem we'd probably write some ad hoc bash logic for it rather than add a testdata_tools feature, but I'm not at all opposed to taking a PR for it.

**Comment by Tagl** [comment]
> It could also apply to the test case just before; either way.

Yeah that's more consistent with group and limits so perhaps smarter to go that way.

> we never expose information of this kind to contestants.

I'm also using testdata_tools for educational tasks at Reykjavík University, that's why I'd like the hint support, been doing it ad hoc so far and it can be a little bothersome.

Another related matter is image files as annotations for testcases, I tend to do it ad hoc but I think it would be easy enough to add that alongside this by defining some visualizer script.

I'm aiming to implement this before preparing a contest that is set in March and will submit a PR before end of year.

**Comment by Tagl** [comment]
One issue is that having it as a separate command doesn't play nice with the parallelism of tc.

**Comment by Tagl** [comment]
> One issue is that having it as a separate command doesn't play nice with the parallelism of tc.

Nevermind that, I was wrong, I'll submit a PR soon.
